### ISSUE TITLE
fix broken ensure=absent

### ISSUE THREAD

**Issue by liamjbennett** [voxpupuli/puppet-windows_firewall#21]
From Scott Kasai:

When you use the $ensure==absent, for deletion command, the $netsh_command you use will break due to addtional information not necessary

```
156c177,183
<         $netsh_command = "C:\\Windows\\System32\\netsh.exe advfirewall
firewall ${fw_action} rule name=\"${display_name}\" ${fw_description}
dir=${direction} action=${action} enable=${enabled}
edge=${allow_edge_traversal} ${allow_context} remoteip=\"${remote_ip}\""

---
 >         if $ensure != 'absent' {
 >           $netsh_command = "C:\\Windows\\System32\\netsh.exe
advfirewall firewall ${fw_action} rule name=\"${display_name}\"
${fw_description} dir=${direction} action=${action} enable=${enabled}
edge=${allow_edge_traversal} ${allow_context} remoteip=\"${remote_ip}\""
 >         }
 >         else
 >         {
 >           $netsh_command = "C:\\Windows\\System32\\netsh.exe
advfirewall firewall ${fw_action} rule name=\"${display_name}\""
 >         }
```

Windows 7 bombed out when 'action=${action}' was in, reporting that:

'action' is not a valid argument for this command

For netsh.exe advfirewall firewall delete...

So if there is a reference call to remove firewall entries, like
this...  It will bomb out due to malformed netsh.exe command request.

**Comment by ofalk** [comment]
Old issue. I've tried to remove rules with ensure=>absent and it worked fine for me. I guess this issue can be closed.

**Comment by adrienb4** [comment]
Hi 
I have the same issue here :

``
Notice: /Stage[main]/Main/Node[desktop-kr51lp2.localdomain]/Windows_firewall::Exception[Toto]/Exec[set rule toto]/returns: 'action' n'est pas un argument valide pour cette commande.
Error: 'C:\Windows\System32\netsh.exe advfirewall firewall delete rule name="toto"  dir=in action= enable=yes edge=no program="C:\toto.exe" remoteip=""' returned 1 instead of one of [0]
Error: /Stage[main]/Main/Node[desktop-kr51lp2.localdomain]/Windows_firewall::Exception[Toto]/Exec[set rule toto]/returns: change from 'notrun' to ['0'] failed: 'C:\Windows\System32\netsh.exe advfirewall firewall delete rule name="toto"  dir=in action= enable=yes edge=no
program="C:\toto.exe" remoteip=""' returned 1 instead of one of [0]
``

You can't use 'action' with 'ensure => absent'.

Adrien

**Comment by adrienb4** [comment]
Hi,

Why you don't authorize the rule deletion if a program name is specified ?

```
if $fw_action == 'delete' and $program == undef {
  $netsh_command = "C:\\Windows\\System32\\netsh.exe advfirewall firewall ${fw_action} rule name=\"${display_name}\" ${fw_description} dir=${direction} ${allow_context} remoteip=\"${remote_ip}\""
} else {
  $netsh_command = "C:\\Windows\\System32\\netsh.exe advfirewall firewall ${fw_action} rule name=\"${display_name}\" ${fw_description} dir=${direction} action=${action} enable=${enabled} edge=${allow_edge_traversal}
```
See this example : 

![image](https://user-images.githubusercontent.com/15191572/36833632-68f1675c-1d30-11e8-83cf-0657f1145c0a.png)
 
I can't delete this rules in one shot with this configuration (see my last post in this issue for error).

```
windows_firewall::exception { 'VNC':
  ensure       => absent,
  direction => 'in',
  display_name => 'all',
  program => 'C:\program files\uvnc bvba\ultravnc\winvnc.exe'
}
````
![image](https://user-images.githubusercontent.com/15191572/36834115-0dfb5716-1d32-11e8-886f-37c1b3f4b13a.png)

Thank

Adrien

**Comment by ofalk** [comment]
@adrienb4 @liamjbennett 
I've created a branch for this (simple) fix. It works for me (tm). Could yout test it and let me know?
https://github.com/voxpupuli/puppet-windows_firewall/tree/fix-rule-deletion-with-prog-name

**Comment by adrienb4** [comment]
Hi oflak

Yes it's working. 
I have apply the same correction as you during my tests.

Thank

**Comment by ofalk** [comment]
Should be fine with https://github.com/voxpupuli/puppet-windows_firewall/pull/61 now.
