### ISSUE TITLE
Windows server 2012 r2

### ISSUE THREAD

**Issue by JasonMcMahan** [voxpupuli/puppet-windows_firewall#48]
You state on the forge you support Windows Server 2012 R2 but the case statement in exceptions.pp line 142 has 
'Windows Server 2012', 'Windows Server 2008', 'Windows Server 2008 R2', 'Windows Vista','Windows 7','Windows 8'

Please add R2 also.
Thank ou

**Comment by blysspluss** [comment]
It'd be nice to see Server 2016 also get added, but definitely 2012 R2 is critical for us.

**Comment by ricardogaspar2** [comment]
Yes, the support for these OS versions critical.

**Comment by ofalk** [comment]
Hi!
Since I'm already working on this module. Do you see any issues with 2012 R2 and 2016? Since I'm not experiencing any problems (at least on 2003 and 2016)
Note that the line in exceptions.pp is only there for special handling of descriptions, that may not exceed 255 characters on 'older' Windows versions (not sure 'bout 2012 R2 - would be nice if someone could test it).
Personally, I'd say this issue could be closed.
